<?php

use App\Http\Controllers\InventoryController;
use Illuminate\Support\Facades\Route;

Route::get('/legacy/materiales-bajo-stock', [InventoryController::class, 'materialesBajoStock']);

// Swagger docs are served at /api/documentation (auto-generated by L5-Swagger)
